import json

from sequence.topology.router_net_topo import RouterNetTopo
from nodes import HetBSMNode, HetQR
from sequence.constants import SPEED_OF_LIGHT
from qfc import QFC
from qchannel import HetQuantumChannel

class YbRouterNetTopo(RouterNetTopo):
    """Class for generating quantum communication network with quantum routers

    Class RouterNetTopo is the child of class Topology. Quantum routers, BSM
    nodes, quantum  channels, classical channels and timeline for simulation
    could be generated by using this class. Different processes in the parallel
    simulation could use the same configuration file to generate network
    required for the parallel simulation.

    Attributes:
        bsm_to_router_map (Dict[str, List[Node]]): mapping of bsm node to two connected routers
        nodes (Dict[str, List[Node]]): mapping of type of node to a list of same type node.
        qchannels (List[QuantumChannel]): list of quantum channel objects in network.
        cchannels (List[ClassicalChannel]): list of classical channel objects in network.
        tl (Timeline): the timeline used for simulation
    """

    MEMO_ARRAY_TYPE = "memo_type"
    ENCODING_TYPE = 'encoding_type'
    WAVELENGTH = 'wavelength'
    ALL_QFCS = 'qfcs'
    CONVERTER = "converter"

    def __init__(self, conf_file_name: str):
        self.qfcs = []
        super().__init__(conf_file_name)
        

    def _load(self, filename: str):
        super()._load(filename)
        with open(filename, 'r') as fh:
            config = json.load(fh)
        self._add_qfcs(config)

    # just adding QFC to channels as converter
    def _add_qchannels(self, config: dict) -> None:
        for qc in config.get(self.ALL_Q_CHANNEL, []):
            src_str, dst_str = qc[self.SRC], qc[self.DST]
            src_node = self.tl.get_entity_by_name(src_str)
            if src_node is not None:
                name = qc.get(self.NAME, f"qc.{src_str}.{dst_str}")
                distance = qc[self.DISTANCE]
                attenuation = qc[self.ATTENUATION]
                converter = qc[self.CONVERTER] # NOTE added this
                qc_obj = HetQuantumChannel(name, self.tl, attenuation, distance, qfc=converter)
                qc_obj.set_ends(src_node, dst_str)
                self.qchannels.append(qc_obj)

    # make QFC not a real desination in terms of router map
    def _map_bsm_routers(self, config):
        for qc in config[self.ALL_Q_CHANNEL]:
            src, dst = qc[self.SRC], qc[self.DST]
            for qfc in config[self.ALL_QFCS]:
                if dst == qfc[self.NAME]:
                    dst = qfc[self.DST]
                    break
            if dst in self.bsm_to_router_map:
                self.bsm_to_router_map[dst].append(src)
            else:
                self.bsm_to_router_map[dst] = [src]

    # creating HetBSMNode and HetQR
    def _add_nodes(self, config: dict):
        for node in config[self.ALL_NODE]:
            seed = node[self.SEED]
            node_type = node[self.TYPE]
            name = node[self.NAME]
            template_name = node.get(self.TEMPLATE, None)
            template = self.templates.get(template_name, {})

            if node_type == self.BSM_NODE:
                others = self.bsm_to_router_map[name]
                node_obj = HetBSMNode(name, self.tl, others, component_templates=template)
            elif node_type == self.QUANTUM_ROUTER:
                memo_size = node.get(self.MEMO_ARRAY_SIZE, 0)
                node_obj = HetQR(name, self.tl, memo_size, component_templates=template)
            else:
                raise ValueError("Unknown type of node '{}'".format(node_type))

            node_obj.set_seed(seed)
            self.nodes[node_type].append(node_obj)
    
    def _add_qfcs(self, config: dict):
        for qfc in config[self.ALL_QFCS]:
            name = qfc[self.NAME]
            destination = qfc[self.DST]
            converter = QFC(name,self.tl,destination)
            converter.add_receiver(self.nodes[self.BSM_NODE][0])
            self.qfcs.append(converter)